clear vna ...
      dmm_1 ...
      dmm_2 ...
      sa ...
      keysight_sg ...
      hp_high_freq_sg ...
      ps_2 ...
      awg ...
      scope ...
      e8257c_sig_gen ...
      hp_sg ...
      hp_33120A_AWG ...
      novatech ...
      lockin_sr844
instrreset